name: Integration Test
on:
  push:
    branches:
     - main
  pull_request:
jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main to compare
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: 'main'

      - uses: actions/checkout@v4
        with:
          path: 'branch'

      - name: Self test
        if: ${{ github.ref != 'refs/heads/main' }}
        id: selftest
        uses: stfc/check-version-action@main
        with:
          app_version_path: "version.txt"
          docker_compose_path: "docker-compose.yml"
          labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
